/**
 * Phase 2 runtime assembly: a generated cordis.yml plus node_modules
 * reachability for the `dsh-jsonrpc-agent` subprocess.
 *
 * The runtime resolves plugin packages from the config file's directory,
 * walking up parent node_modules. The generated config lives in the
 * extension's global storage, so we create a Windows junction (no admin
 * needed) from `<storage>/dsh-runtime/node_modules` to the repo's
 * `examples/node_modules` — the single workspace member that declares the
 * union of every cordis.yml plugin (see pnpm-workspace.yaml's `examples`
 * comment). This mirrors dsh's own `healProfilesModuleFallback`.
 */

import { mkdirSync, readlinkSync, statSync, symlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/** The extension-side JSON-RPC runtime bin (source-launched from the repo). */
export function jsonrpcAgentCommand(repoPath: string, nodePath?: string): { command: string; args: string[] } {
  // System node, not process.execPath: inside the Extension Host the latter
  // is Code.exe whose embedded node breaks tsx's tsconfig-paths resolution.
  return {
    command: nodePath ?? 'node',
    args: ['--import', 'tsx/esm', join(repoPath, 'packages', 'examples', 'jsonrpc-demo', 'src', 'bin.ts')],
  }
}

/**
 * Ensures `<storage>/dsh-runtime/cordis.yml` exists and its node_modules is
 * a junction to the repo's `examples/node_modules`. Returns the config path.
 * @throws Error when the repo's examples node_modules is missing.
 */
export function ensureRuntimeConfig(storagePath: string, repoPath: string): string {
  const runtimeDir = join(storagePath, 'dsh-runtime')
  const configPath = join(runtimeDir, 'cordis.yml')
  const nmTarget = join(repoPath, 'examples', 'node_modules')
  const nmLink = join(runtimeDir, 'node_modules')

  mkdirSync(runtimeDir, { recursive: true })
  writeFileSync(configPath, CORDIS_YML_TEMPLATE, 'utf8')

  try {
    const st = statSync(nmLink)
    if (st.isDirectory() && readlinkOf(nmLink) !== nmTarget) {
      throw new Error('existing node_modules is not the expected junction')
    }
  } catch (err) {
    // Missing or mismatched: (re)create the junction.
    try {
      symlinkSync(nmTarget, nmLink, 'junction')
    } catch (inner) {
      throw new Error(
        `cannot link ${nmLink} → ${nmTarget}: ${messageOf(inner)}. ` +
          `The dsh repo must be installed (examples/node_modules) before phase 2 can run.`,
      )
    }
  }
  return configPath
}

function readlinkOf(path: string): string {
  try {
    return readlinkSync(path)
  } catch {
    return ''
  }
}

/**
 * Composition for an unattended JSON-RPC agent, trimmed from
 * `examples/jsonrpc-agent/cordis.yml`. Environment overrides:
 *  - DSH_SESSION_ROOT: session log location (defaults to ./sessions)
 *  - DSH_CWD: the agent's working directory (defaults to process cwd)
 *  - DSH_SYSTEM_PROMPT: persona (defaults to the base persona)
 */
const CORDIS_YML_TEMPLATE = `# Generated by dsh-vscode (phase 2 runtime).
# stdout is reserved for JSON-RPC; do not add a console logger or terminal UI.

- id: sdk-jsonrpc-server
  name: '@deepseek-ai/dsh-sdk-jsonrpc-server'
  config:
    maxTokensAsSuccess: !!js "process.env.DSH_MAX_TOKENS_AS_SUCCESS === undefined ? true : JSON.parse(process.env.DSH_MAX_TOKENS_AS_SUCCESS)"

- id: llm-deepseek
  name: '@deepseek-ai/dsh-llm-deepseek'
  config:
    thinking: enabled
    reasoningEffort: max

- id: subprocess
  name: '@deepseek-ai/dsh-subprocess-local'

- id: bash
  name: '@deepseek-ai/dsh-bash-local'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()
    timeoutMs: 60000

- id: agent-spine
  name: '@deepseek-ai/dsh-agent-spine-demo'
  config:
    persona: !!js process.env.DSH_SYSTEM_PROMPT ?? 'You are a coding agent.'
    workspaceContext: false
    skills:
      enabled: false
    toolBash:
      enableRunInBackground: false
    toolJobs: false

- id: sessions
  name: '@deepseek-ai/dsh-session-persistence-jsonl'
  config:
    root: !!js process.env.DSH_SESSION_ROOT ?? './sessions'
    compression: 'none'

- id: session-checkpoints
  name: '@deepseek-ai/dsh-session-checkpoint-policy'

- id: subagent
  name: '@deepseek-ai/dsh-subagent'

- id: subagent-spawn-in-process
  name: '@deepseek-ai/dsh-subagent-spawn-in-process'
  config:
    providerName: spawn

- id: tool-subagent
  name: '@deepseek-ai/dsh-tool-subagent'
  config:
    provider: spawn
    toolName: subagent
    enableRunInBackground: false

- id: tool-todo
  name: '@deepseek-ai/dsh-tool-todo'
  config:
    allowParallelInProgress: true

- id: fs-local
  name: '@deepseek-ai/dsh-fs-local'
  config:
    cwd: !!js process.env.DSH_CWD ?? process.cwd()

- id: fs-observation-policy
  name: '@deepseek-ai/dsh-fs-observation-policy'

- id: tool-fs
  name: '@deepseek-ai/dsh-tool-fs'

- id: token-meter
  name: '@deepseek-ai/dsh-token-meter'

- id: compaction-basic
  name: '@deepseek-ai/dsh-compaction-basic'
  config:
    thresholdRatio: 0.8
    retainRatio: 0.16
    maxTokens: 8192
    compactionRetries: 1
`

function messageOf(err: unknown): string {
  return err instanceof Error ? err.message : String(err)
}
